import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipe Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gradient-to-r from-indigo-500 to-cyan-500 w-screen h-screen">
      <body className={inter.className}>
         <header>
          <NavBar></NavBar>
        </header>
        {children}
      </body>
    </html>
  );
}
